### ISSUE TITLE
Warning coverage is not shared in gradle with jacoco 

### ISSUE THREAD

**Issue by oussamamessaoudi** [qodana/qodana-coverage#16]
The coverage is not shared and I have this warning in log !!!!

WARNING! No coverage was computed, probably coverage file does not match the sources. Please check your settings

```yml

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build & Test
        run: ./gradlew clean build test
      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/code-coverage
  static-analysis:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Download build folder
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: .qodana/code-coverage
      - name: Static analysis
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          upload-result: true

```

```groovy

test {
    finalizedBy jacocoTestReport
    useJUnitPlatform()
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = false
        csv.required = false
        xml.outputLocation = layout.buildDirectory.file('reports/jacoco/code-coverage/result.xml')
    }
}
```

@hybloid @tiulpin @evgenyim @qodana-bot
